### PR TITLE
Do not override base user agent

### PR DESCRIPTION
**Pull request by weppos**
See https://github.com/aetrion/dnsimple-go#26

### CODE REVIEW

**Comment by weppos** [comment]
@jacegu the feature is there, but I honestly have no idea how to test it (and if it's possible).

**Comment by weppos** [comment]
@jacegu I made some research. What I found is that:

1. excvr doesn't support it
2. in all cases I've checked, including httpoison tests theirselves, the common approach is to use mocks. In fact, httpoison includes a mock library

        {:meck, "~> 0.8.2", only: :test},

We have two options here:

1. We just move on, and we don't test this specific change
2. We introduce the dependency on the mock library

Preferences?

**Comment by jacegu** [comment]
@weppos I rather not test it than introducing a new dependency.

If I come with a solution to test it without introducing the dependency I'll let you know.

**Comment by weppos** [comment]
👍

**Pull request merged**
